### ISSUE TITLE
Better error messages during verification of rules

### ISSUE THREAD

**Issue by trishankatdatadog** [in-toto/in-toto#228]
**Description of issue or feature request**:

Presently, it takes a bit of detective work to understand exactly why artifacts failed to match given rules.

For example, supposing an artifact matched a filename pattern, but was supposed to MATCH a product or material from some other step, and was instead observed to be MODIFIED, then this is not clear at all, and requires manual inspection by the user.

At the same time, these diagnostic error messages should only be reported on stderr for artifacts that violate given rules.

**Current behavior**:

Error messages are misleading.

**Expected behavior**:

Error messages should be as precise as possible.

**Comment by michizhou** [comment]
@trishankatdatadog I would be more than happy to take on this issue. I just need a bit more context in terms of which file (with full repo filepath) generates the error messages and any supporting advice or documentation that could help me make the messages more specific. Please let me know. Thanks!

**Comment by lukpueh** [comment]
Artifact rules are processed in [in-toto/verifylib.py](https://github.com/in-toto/in-toto/blob/develop/in_toto/verifylib.py) (see `verify_item_rules` and `verify_*_rule` functions). Please also take a look #238 and in-toto/docs#11, which should give you a good overview of the current way artifact rules are processed.

**Comment by michizhou** [comment]
@lukpueh @trishankatdatadog Just as a heads up, I just made a new PR that should at least partially resolve this issue. I also noticed that changing the `verify_delete_rule` function implementation (which is in alignment with the `FIXME` goals of in-toto/in-toto#204) is causing issues in `test_verifylib.py` since some of the tests in that file rely on RuleVerificationError exceptions being raised by the `verify_delete_rule` function. We might want to rethink changing the `verify_delete_rule` function implementation if that is the case. Feel free to share your thoughts on this and other issues.

**Comment by michizhou** [comment]
@lukpueh My apologies for not getting back to you earlier, but I have recently addressed your most recent concerns on my prior PR (#242) though a new PR (#243) I created. Please look it over and let me know if you need me to make any further changes. Thanks!

**Comment by michizhou** [comment]
@lukpueh I just pushed some recent changes that should give more useful contextual information for the tracebacks on rule processing in the verification error messages. Please let me know if there are any additional changes I would need to make in your review. Thanks!

**Comment by lukpueh** [comment]
Fixed with #243 and #262
