### ISSUE TITLE
GPG: Warn if expiration subpacket is not hashed.

### ISSUE THREAD

**Issue by SantiagoTorres** [in-toto/in-toto#281]
**Description of issue or feature request**:
When verifying expiration dates on keys, a hashed or unashed subpacket is parsed to obtain the date in which the key is expired.

**Current behavior**: Currently this date is parsed properly, and hashed subpackets are prioritized over unhashed ones.

**Expected behavior**: It would be nice to use the logger faciilty to warn the user when the unhashed subpackets are used, as this may be an issue with their pgp client exporting a weakly-configured key.

**Comment by lukpueh** [comment]
IIRC RFC4880 states that any subpacket may be hashed or unhashed, since we use other subpackets too (issuer, fingerprint, primary user id, signature creation time) we might want to warn on those too.

We also have to decide if we want to warn once (e.g. on export) or keep the a hashed/unhashed flag and warn, whenever the corresponding information is used (subpackets are currently extracted in `in_toto.gpg.common.parse_signature_packet`).

**Comment by joshuagl** [comment]
It looks like this was at least partially resolved in #288 / c4da7995. Should this issue be closed or is there work left to do here?

**Comment by SantiagoTorres** [comment]
Hi @joshuagl, yes, you're right. Thanks!
