### ISSUE TITLE
any plans to continue work on this project?

### ISSUE THREAD

**Issue by nathanawmk** [in-toto/in-toto#484]
I believe that if in-toto is adopted at scale, many of the software supply chain hacks would not have happened. 

It seems like work has stopped on this - are there plans to continue work on in-toto?

**Comment by adityasaky** [comment]
Hi @nathanawmk, work on in-toto has not halted at all. This implementation is seeing lower activity because of a couple of reasons:
1. It's had a stable release, and is therefore not where newer integrations are "tested". Stability is paramount here.
2. A lot of the current usage of in-toto is in the cloud native space, and as a result the [Go implementation](https://github.com/in-toto/in-toto-golang) is more active, and the current "testbed".

We use [in-toto Enhancements (ITE)](https://github.com/in-toto/ite) to track major changes and integrations. In particular, [ITE-6](https://github.com/in-toto/ITE/blob/master/ITE/6/README.md) which enables generic attestation types, which you can track [here](https://github.com/in-toto/attestation), may be of interest to you as it's been used in [SLSA](https://slsa.dev) and Tekton Chains, among other places. Further, [ITE-7](https://github.com/in-toto/ITE/pull/21) enables integrations with broader identity provider ecosystems, adding support for x509 certificates, enabling the use of SPIFFE/SPIRE (there's implementation support for this on in-toto-golang's latest prerelease), as well as the use of Sigstore's Fulcio further down the line.

To stay updated with the latest in-toto happenings. please join the [CNCF slack workspace](https://slack.cncf.io) where we have an #in-toto channel, our [mailing list](https://groups.google.com/g/in-toto-public), and keep an eye on our [roadmap](https://github.com/in-toto/docs/blob/master/ROADMAP.md) and reviews. The [latest roadmap review](https://github.com/in-toto/docs/blob/master/roadmap-reviews/2022/review_1_december_21.md) was published yesterday. Finally, please feel free to join us for our [monthly community meetings](https://hackmd.io/@lukpueh/ry_e70Qqw).

**Comment by adityasaky** [comment]
I do want to add that if there's a particular feature you're looking for in this implementation, feel free to open an issue or submit a PR. If you'd like to discuss it beforehand, you can reach us via the Slack workspace or the mailing list. :)
