### ISSUE TITLE
Add support for ecdsa key-type

### ISSUE THREAD

**Issue by danbev** [in-toto/in-toto#519]
**Description of issue or feature request**:
Currently, commands like `in-toto-sign`, and `in-toto-run` support a command line option named `--key-type`:
```console
 -t {rsa,ed25519}, --key-type {rsa,ed25519}
```
Would it be possible to add support for ECDSA key types?

The reason for asking this that it would be nice to be able to use keys generated by `cosign` but currently it looks like `cosign` [only generates ECDSA-P256 keys and uses SHA256 hashes](https://github.com/sigstore/cosign#intentionally-missing-features).

I'm not sure if this helps or not, but it looks like `securesystemslib` has support for [KEY_TYPE_ECDSA](https://github.com/secure-systems-lab/securesystemslib/blob/master/securesystemslib/__init__.py#L19).

**Current behavior**:
N/A

**Expected behavior**:
N/A

**Comment by adityasaky** [comment]
Thanks for opening the issue, @danbev! Yes, the CLI tools in in-toto-python should be updated to include / indicate support for ECDSA keys and it should be a small diff overall. I say "indicate" because the underlying `in_toto_run` API already supports ECDSA keys because the securesystemslib API it uses in turn [supports ECDSA keys](https://github.com/secure-systems-lab/securesystemslib/blob/4e63f9927f65ffda01d3d7ade136a4dd1392a1ac/securesystemslib/keys.py#L605). See:

```
>>> from securesystemslib.interface import import_ecdsa_privatekey_from_file as i
>>> key = i("key")
>>> key["keytype"]
'ecdsa'
>>> key["scheme"]
'ecdsa-sha2-nistp256'
>>> from in_toto.runlib import in_toto_run
>>> in_toto_run("test", [], [], [], signing_key=key)
{
 "signatures": [
  {
   "keyid": "afaa2cf6da2d15d6574783baffeb8c3f115348004712644c848f4dab7e5728e1",
   "sig": "3046022100c94e05baffe5a68212ccee6f486a461c64e3dbecdfccaee651dc347558fc2d00022100920717e22f0edce0b140d0c57400761ff790f4cc57496f870d097e452bda146a"
  }
 ],
 "signed": {
  "_type": "link",
  "byproducts": {},
  "command": [],
  "environment": {},
  "materials": {},
  "name": "test",
  "products": {}
 }
}
```

Do you think you could submit a patch to the CLI tooling and the accompanying docs?

**Comment by danbev** [comment]
> Do you think you could submit a patch to the CLI tooling and the accompanying docs?

I'll take a shot at doing this :+1:
